size_logo: "40x40"
minimum_password_length: 6
per_page: 8
activity_length: 15
content_length: 30
admin_content_length: 70
book_title_length: 30
limit_element: 6
rate:
  load_five_star: 5
  load_four_star: 4
  load_three_star: 3
  load_two_star: 2
  load_one_star: 1
  list_rate:
    - load_five_star
    - load_four_star
    - load_three_star
    - load_two_star
    - load_one_star
book:
  list_status:
    - reading
    - read
    - favorite
  list_book:
    - list_reading
    - list_read
    - list_favorite
  author: author
  list_filter:
    - all
    - reading
    - read
    - favorite
max_rate: 5
